Artist.create(name: "Drake")
Artist.create(name: "Kanye")
Artist.create(name: "Jay-Z")
Song.create(title: "Dirt Off Ya Shoulder", artist_id: 3)
Song.create(title: "Gold Digga", artist_id: 2)
Song.create(title: "Best I Ever Had", artist_id: 1)
